### ISSUE TITLE
Exception when trying to run it

### ISSUE THREAD

**Issue by G4-Synix** [codename0og/rvc-realtime-voice-changer#1]
File "C:\Users\axe\AppData\Local\Programs\Python\Python312\Lib\dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

shows this exception when trying to run

**Comment by codename0og** [comment]
You can't use python 3.12.x.
For RVC ( tho that's been sorta experimentally changed so 3.11 can be used as well, iirc ) and the voice-changer, you gotta be having 3.10.6 as that's essentially why you get the error.

in a short, you gotta get python 3.10.6 as that's the most stable and tested for the voice changer and rvc ( ideally, clean python and requirements installation to avoid potential conflicts
