### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by KarinMiku** [codename0og/rvc-realtime-voice-changer#2]
![image](https://github.com/codename0og/rvc-realtime-voice-changer/assets/51896289/ed670da0-13d2-4af0-a6e7-cdba8d1ec5fb)
im using an rtx 4070 and tried using both "requirements" files, NVIDIA and COMPATIBILITY VER, both of them gave me the same error, at first i thought it was due to my python version, cuz i had 3.10.6 and 3.7 installed, so i uninstalled both, reboot and then installed only the 3.10.6 ver but the issue ended up being the same

**Comment by codename0og** [comment]
Sorry my dude. I heavily overlooked one thing during packaging.
Please make a folder called " infer " in the main dir of the voice changer and move " lib " and " modules " folders to that " infer folder ".
( Will fix it in the package itself soon ) 

Thanks for letting me know! 
Also, sorry for the delay. Got overtaken by elden ring lol.
